# Generated by Django 4.2.6 on 2023-10-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('familyName', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
